version: "3.8"
services:
  customer-microservice:
    image: skeres95250/alpine_customer:latest
    network_mode: host
    environment:
      server.port: 8081
      logging.level.root: DEBUG
      spring.cloud.inetutils.timeout-seconds: 10
      eureka.client.service-url.defaultZone: http://192.168.122.99:8761/eureka
